import Head from 'next/head'
import { useContext } from 'react'
import { ContractContext } from './../context/contract'

export default function Admin() {
  const contractContext = useContext(ContractContext)
  return (
    <div>
      <Head>
        <title>Guess-Number管理后台</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        {
          contractContext.accounts.length > 0 ? (<div >
            {contractContext.accounts[0]}, I have {contractContext.ownToken} GN
          </div>) : (
            <div onClick={contractContext.onAdminConnect}>connect admin wallet</div>
          )
        }
        {
          contractContext.accounts.length > 0 ? (
            <div>
              <div>
                <input value={contractContext.title} onChange={contractContext.onChangeTitle}></input>标题
              </div>
              <div>
                <input value={contractContext.reward} onChange={contractContext.onChangeReward}></input>将金
              </div>
              <div>
                <input value={contractContext.maxUserJoinedNumber} onChange={contractContext.onChangeUserJoinedMaxNumber} disabled={contractContext.nowStatus !== 0}></input>最多用户参与数
              </div>
              <div>
                <input value={contractContext.maxUserRewardNumber} onChange={contractContext.onChangeUserRewardMaxNumber} disabled={contractContext.nowStatus !== 0}></input>最多用户中奖人数
              </div>
              <div>
                <button onClick={contractContext.saveData}>保存</button>
              </div>
              {
                contractContext.nowStatus === 2 ? (
                  <div>
                    <div>
                      <input value={contractContext.hitNumber} onChange={contractContext.onChangeHitNumber}></input>获奖数字
                    </div>
                    <div>
                      <button onClick={contractContext.saveHitNumber}>设置获奖数字</button>
                    </div>
                  </div>
                ) : ''
              }
              {
                contractContext.nowStatus === 3 ? (
                  <div>幸运数字：{contractContext.hitNumber}</div>
                ) : ''
              }
              <div>
                {
                  contractContext.nowStatus !== 0 ? (
                    <button>重新</button>
                  ) : ''
                }
                {
                  contractContext.nowStatus === 0 ? (
                    <button onClick={contractContext.startGame}>开始游戏</button>
                  ) : ''
                }
                {
                  contractContext.nowStatus !== 2 ? (
                    <button onClick={contractContext.prepareOpenReward}>设置幸运数字</button>
                  ) : ''
                }
                {
                  contractContext.nowStatus !== 3 ? (
                    <button onClick={contractContext.announceReward}>公布数字</button>
                  ) : ''
                }
              </div>
            </div>
          ) : ''
        }
      </main>
    </div>
  )
}