import Head from 'next/head'
import { useContext } from 'react'
import { ContractContext } from './../context/contract'

export default function Client() {

  const contractContext = useContext(ContractContext)

  return (
    <div>
      <Head>
        <title>Guess-Number</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        {
          contractContext.accounts.length > 0 ? (
              <div>{contractContext.accounts[0]}, I have {contractContext.ownToken} GN</div>
            ) : (
            <div onClick={contractContext.onConnect}>connect wallet</div>
          )
        }
        {
          contractContext.nowStatus === 0 && contractContext.accounts.length > 0 ? (
            <div>游戏暂未开始</div>
          ) : ''
        }
        {
          contractContext.nowStatus === 1 ? (
            <div>进行中</div>
          ) : ''
        }
        {
          contractContext.owStatus === 2 ? (
            <div>待开奖</div>
          ) : ''
        }
        {
          contractContext.nowStatus === 3 ? (
            <div>已结束</div>
          ) : ''
        }
        {
          contractContext.nowStatus !== 0 ? (
            <div>
              <div>标题：{contractContext.title}</div>
              <div>奖励：{contractContext.reward} GN</div>
              <div>最多参与人数：{contractContext.maxUserJoinedNumber}</div>
              <div>最多获奖人数：{contractContext.maxUserRewardNumber}</div>
              <div>当前参与人数：{contractContext.joinList.length}人</div>
              {
                contractContext.nowStatus === 2 || contractContext.nowStatus === 3 ? (
                  <div>你猜的数字：{contractContext.userGuessNumber}</div>
                ) : ''
              }
              {
                contractContext.nowStatus === 3 ? (
                  contractContext.isHitReward ? (
                    <div>恭喜，您已获奖</div>
                  ) : (
                    <div>对不起，您未获奖</div>
                  )
                ) : ''
              }
              <div>
                {
                  contractContext.nowStatus === 1 ? (
                    <div>
                      <input value={contractContext.userGuessNumber} onChange={contractContext.onChangeUserGuessNumber} disabled={!contractContext.canUserGuess}></input>
                      <button onClick={contractContext.onGuessANumber} disabled={!contractContext.canUserGuess}>点击参与</button>
                    </div>
                  ) : ''
                }
              </div>
            </div>
          ) : ''
        }
      </main>
    </div>
  )
}