import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App2</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main style={{display:"flex"}}>
        <div style={{marginRight:"10px"}}><a href="/client">用户端</a></div>
        <div><a href="/admin">管理员</a></div>
      </main>
    </div>
  )
}
